import os
from setuptools import find_packages, setup

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'README.md')) as readme:
    README = readme.read()

with open(os.path.join(PROJECT_ROOT, 'requirements.txt')) as f:
    requirements = [line.strip() for line in f if line.strip() and not line.startswith('#')]

# allow setup.py to be run from any path
os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir)))

setup(
    name='django-deep-translator',
    version='1.6.0',
    packages=find_packages(),
    install_requires=requirements,
    include_package_data=True,
    license='MIT License',
    description='Automatically translate the pot (`.po`) files generated by django\'s '
                'makemessages command built on top of python deep-translator package',
    long_description=README,
    long_description_content_type='text/markdown',
    url='https://github.com/Monolynx/monolynx-django-deep-translator',
    author='Grace Amondi',
    author_email='miswa.grace@gmail.com',
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
)